config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.authtoken import views as authtoken_views

from players.urls import router as players_router
from . import views


urlpatterns = [
    path('api/', include(players_router.urls)),
    path('api/login/', authtoken_views.obtain_auth_token),

    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('', include('players.urls')),
]

players/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views


router = DefaultRouter()
router.register('dashboard', views.DashboardViewSet, basename='dashboard')
router.register('games', views.GameViewSet, basename='games')
router.register('players', views.PlayerViewSet, basename='players')


urlpatterns = [
    path('latest_game_form/', views.latest_game_form, name='latest_game_form'),
    path('games/<int:pk>/', views.game_details, name='game_details'),
    path('players/<int:pk>/', views.player_details, name='player_details'),
]

players/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Player(AbstractUser):
    display_name = models.CharField(max_length=100, blank=True)


class Hero(models.Model):
    name = models.CharField(max_length=30)
    winrate = models.DecimalField(max_digits=4, decimal_places=1)
    num_games = models.IntegerField()

    def __str__(self):
        return self.name

    @classmethod
    def update_stats(cls, hero):
        global_num_games_won = GamePlayer.objects.filter(
            result=GamePlayer.WIN,
            hero=hero,
        ).count()
        global_num_games_lost = GamePlayer.objects.filter(
            result=GamePlayer.LOST,
            hero=hero,
        ).count()
        global_num_games = global_num_games_won + global_num_games_lost
        try:
            global_winrate = (global_num_games_won / global_num_games) * 100
        except ZeroDivisionError:
            global_winrate = 0
        hero = hero
        hero.num_games = global_num_games
        hero.winrate = global_winrate
        hero.save()


class PlayerHero(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='player_heroes')
    hero = models.ForeignKey(Hero, on_delete=models.CASCADE, related_name='player_heroes')
    winrate = models.DecimalField(max_digits=4, decimal_places=1)
    num_games = models.IntegerField()

    def __str__(self):
        return f'{self.player} - {self.hero}'

    @classmethod
    def update_stats(cls, player, hero):
        num_games_won = GamePlayer.objects.filter(
            player=player,
            result=GamePlayer.WIN,
            hero=hero,
        ).count()
        num_games_lost = GamePlayer.objects.filter(
            player=player,
            result=GamePlayer.LOST,
            hero=hero,
        ).count()
        num_games = num_games_won + num_games_lost
        try:
            winrate = (num_games_won / num_games) * 100
        except ZeroDivisionError:
            winrate = 0
        PlayerHero.objects.update_or_create(
            player=player,
            hero=hero,
            defaults={
                'winrate': winrate,
                'num_games': num_games,
            }
        )


class Game(models.Model):
    date = models.DateTimeField()
    duration = models.DurationField()

    def __str__(self):
        return f'{self.date} - {self.duration}'


class GamePlayer(models.Model):
    WIN = 1
    LOST = 2
    INVALID = 3

    RESULT_TYPES = [
        (WIN, 'Win'),
        (LOST, 'Lost'),
        (INVALID, 'Invalid'),
    ]

    BLUE = 1
    RED = 2

    TEAM_SIDE = [
        (BLUE, 'Blue'),
        (RED, 'Red'),
    ]

    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='game_players')
    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='game_players')
    hero = models.ForeignKey(Hero, on_delete=models.CASCADE, related_name='game_players')
    result = models.PositiveSmallIntegerField(choices=RESULT_TYPES)
    team = models.PositiveSmallIntegerField(choices=TEAM_SIDE)
    kills = models.IntegerField()
    deaths = models.IntegerField()
    assists = models.IntegerField()

    def __str__(self):
        return f'{self.player} - {self.hero} - {self.team}'

# A game can involve 10 players, and they don't have to enter their own game if someone else entered it.


# 1. Separate entry for all players: Hero, K/D/A.
# 2. 2 groups of 5, winning side and losing side

# Break down the Game model into two models,
# Game (containing date and duration) and
# GamePlayer (foreign keys to Game and Player, and hero/result/kda).
# The goal is to be able to enter one game that ties to multiple players.

players/forms.py
from django.forms import ModelForm, formset_factory
from django.utils import timezone
from django.forms.fields import DateTimeField
from django import forms

from .models import GamePlayer, Game


# creating a form for recording games

class GamePlayerForm(forms.ModelForm):
    class Meta:
        model = GamePlayer
        fields = [
            'team',
            'result',
            'player',
            'hero',
            'kills',
            'deaths',
            'assists',
        ]

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = [
            'date',
            'duration',
        ]


'''class GamePlayerForm(forms.Form):
    WIN = 1
    LOST = 2
    INVALID = 3

    RESULT_TYPES = [
        (WIN, 'Win'),
        (LOST, 'Lost'),
        (INVALID, 'Invalid'),
    ]

    BLUE = 1
    RED = 2

    TEAM_SIDE = [
        (BLUE,'Blue'),
        (RED,'Red'),
    ]

    team = forms.CharField(widget=forms.Select(choices=RESULT_TYPES))
    result = forms.CharField(widget=forms.Select(choices=TEAM_SIDE))
    player = forms.CharField()
    hero = forms.CharField()
    kills = forms.IntegerField()
    deaths = forms.IntegerField()
    assists = forms.IntegerField()
'''
#make another form for game
#then render the 2 forms together
#1 Game form, 10 GamePlayer forms later task

players/views.py
from django.shortcuts import redirect, render
from django.utils import timezone
from django.forms import modelformset_factory
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.decorators import action
import django_filters

from .serializers import GamePlayerSerializer, GameSerializer, HeroSerializer, PlayerSerializer, PlayerHeroSerializer
from .models import Player, PlayerHero, Game, Hero, GamePlayer
from .forms import GameForm, GamePlayerForm

# 1. Make sure to place your exception handler as close to the source of the exception as possible
# 2. In general, don't write too long functions
# See if you can extract distinct pieces of logic into their own functions


class DashboardViewSet(viewsets.ViewSet):
    def get_user(self):
        return self.request.user

    @action(detail=False, url_path='top-5-heroes')
    def top_5_heroes(self, request):
        queryset = PlayerHero.objects.filter(player=request.user, num_games__gte=1).order_by(
            '-winrate', '-num_games', 'hero__name'
        )[:5]
        serializer = PlayerHeroSerializer(queryset, many=True)
        return Response(serializer.data)

    @action(detail=False, url_path='top-5-heroes-global')
    def top_5_heroes_global(self):
        queryset = Hero.objects.filter(num_games__gte=1).order_by('-winrate', '-num_games', 'name')[:5]
        serializer = HeroSerializer(queryset, many=True)
        return Response(serializer.data)

    @action(detail=False, url_path='last-5-games')
    def last_5_games(self, request):
        queryset = GamePlayer.objects.filter(player=request.user).order_by('-game__date')[:5]
        serializer = GamePlayerSerializer(queryset, many=True)
        return Response(serializer.data)


class GameFilter(django_filters.FilterSet):
    player = django_filters.NumberFilter('game_players__player')

    class Meta:
        model = Game
        fields = ['player']


class GameViewSet(viewsets.ModelViewSet):
    queryset = Game.objects.all()
    serializer_class = GameSerializer
    filter_class = GameFilter


class PlayerViewSet(viewsets.ModelViewSet):
    queryset = Player.objects.all()
    serializer_class = PlayerSerializer

    # @action(detail=False)
    # def top_5_heroes(self, request, pk):
    #     queryset = PlayerHero.objects.get(pk=pk)
    #     serializer = PlayerHeroSerializer(queryset, many=True)
    #     return Response(serializer.data)


# class PlayerHeroViewSet(viewsets.ModelViewSet):
#     queryset = PlayerHero.objects.all()
#     serializer_class = PlayerHeroSerializer


def latest_game_form(request):
    game_form = GameForm(initial={'date': timezone.now()})
    GamePlayerFormSet = modelformset_factory(GamePlayer, form=GamePlayerForm, extra=5)
    winner_formset = GamePlayerFormSet(
        queryset=GamePlayer.objects.none(), initial=[{'game': game_form}], prefix='winner',
    )
    loser_formset = GamePlayerFormSet(
        queryset=GamePlayer.objects.none(), initial=[{'game': game_form}], prefix='loser',
    )
    if request.method == 'POST':
        game_form = GameForm(request.POST)
        winner_formset = GamePlayerFormSet(request.POST, prefix='winner')
        loser_formset = GamePlayerFormSet(request.POST, prefix='loser')
        if game_form.is_valid():
            game = game_form.save()
        if winner_formset.is_valid():
            instances = winner_formset.save(commit=False)
            for instance in instances:
                instance.game = game
                instance.save()
                PlayerHero.update_stats(instance.player, instance.hero)
                Hero.update_stats(instance.hero)
        if loser_formset.is_valid():
            instances = loser_formset.save(commit=False)
            for instance in instances:
                instance.game = game
                instance.save()
                PlayerHero.update_stats(instance.player, instance.hero)
                Hero.update_stats(instance.hero)

        return redirect('home')
    else:
        print(game_form.errors, winner_formset.errors)

    context = {
        'game_form': game_form,
        'winner_formset': winner_formset,
        'loser_formset': loser_formset,
        }

    return render(request, 'players/latest_game_form.html', context)


def game_details(request, pk):
    games = Game.objects.get(pk=pk)

    context = {
        'games': games,
    }

    return render(request, 'players/game_details.html', context)


def player_details(request, pk):
    players = Player.objects.get(pk=pk)
    player_games = players.game_players.order_by('-game__date')

    context = {
        'players': players,
        'player_games': player_games,
        }

    return render(request, 'players/player_details.html', context)

players/templates/players/game_details.html
{% extends "base.html" %}

{% block title %}Game Details{% endblock %}

{% block content %}
    <h2>Game Overview</h2>

    <table>
        <thead>
            <tr>
                <td>Result</td>
                <th>Team</th>
                <th>Player</th>
                <th>Hero</th>
                <th>K/D/A</th>
            </tr>
        </thead>
        <tbody>
            {% for game in games.game_players.all %}
                <tr>
                    <td>{{ game.get_result_display }}</td>
                    <td>{{ game.get_team_display }}</td>
                    <td><a href="{% url "player_details" game.player.pk %}">{{ game.player }}</td>
                    <td>{{ game.hero }}</td>
                    <td>{{ game.kills }}/{{ game.deaths }}/{{ game.assists }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td>Player name</td>
                    <td>No game details yet!</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

players/templates/players/latest_game_form.html
{% block title %}<title>Enter Game</title>{% endblock %}
<h1>Welcome, {{ request.user.display_name }} ({{ request.user.username}})</h1>
    <form method="POST" action="{% url "logout" %}">
        {% csrf_token %}
        <button type="submit">Log Out</button>
        <a href="{% url "home" %}">Home</a>
    </form>
{% block content %}
<form method = "POST">
    {% csrf_token %}
    <div>
        {{ game_form }}
    </div>
    <div>
        <br>
        <table>
            <thead>
              <tr>
                <th align=left><h2>Winning Team</h2></th>
                <th align=left><h2>Losing Team</h2></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                    <table>
                        <thead>
                            {{ winner_formset.management_form }}
                                {% for form in winner_formset %}
                                    {% if forloop.first %}
                                        {% for field in form.visible_fields %}
                                            <th>{{ field.label_tag }}</th>
                                        {% endfor %}
                                    {% endif %}
                        </thead>
                            <tbody>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <td>{{ field }}</td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                            </tbody>
                    </table>
                </td>
                <td>
                    <table>
                        <thead>
                            {{ loser_formset.management_form }}
                                {% for form in loser_formset %}
                                    {% if forloop.first %}
                                        {% for field in form.visible_fields %}
                                            <th>{{ field.label_tag }}</th>
                                        {% endfor %}
                                    {% endif %}
                        </thead>
                            <tbody>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <td>{{ field }}</td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                            </tbody>
                    </table>
                </td>
              </tr>
            </tbody>
          </table>
          <br>
    <input type="submit" value="Save">
</form>
{% endblock %}

players/templates/players/player_details.html
{% extends "base.html" %}

{% block title %}Player Details{% endblock %}

{% block content %}
    <h2>Player's Hero Details</h2>
    <table>
        <thead>
            <tr>
                <th>Hero</th>
                <th>Number of games</th>
                <th>Winrate</th>
            </tr>
        </thead>
        <tbody>
            {% for player in players.player_heroes.all%}
                <tr>
                    <td>{{ player.hero }}</td>
                    <td>{{ player.num_games }}</td>
                    <td>{{ player.winrate }}%</td>
                </tr>
            {% empty %}
                <tr><td colspan="6">No hero stats yet!</td></tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Player's Games</h2>
    <table>
        <thead>
            <tr>
                <th>Team</th>
                <th>Your Hero</th>
                <th>Result</th>
                <th>K/D/A</th>
                <th>Date</th>
                <th>Duration</th>
            </tr>
        </thead>
        <tbody>
            {% for player_game in player_games %}
                <tr>
                    <td>{{ player_game.get_team_display }}</td>
                    <td>{{ player_game.hero }}</td>
                    <td>{{ player_game.get_result_display}}</td>
                    <td>{{ player_game.kills }}/{{ player_game.deaths }}/{{ player_game.assists }}</td>
                    <td><a href="{% url "game_details" player_game.game.pk %}">{{ player_game.game.date }}</a></a></td>
                    <td>{{ player_game.game.duration }}</td>
                </tr>
            {% empty %}
                <tr><td colspan="6">No games yet!</td></tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}